#!/bin/sh
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --default-domain=per_recipient_sent_folders --no-wrap --add-comments=i18n"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_OLD_GETTEXT ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
fi

xgettext ${XGETTEXT_OPTIONS} *.php --output=per_recipient_sent_folders.pot
